downloads: ~/.ansible-downloads/

# Dock
configure_dock: true

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Maps
  - Safari
  - Photos
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 1
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2

# Homebrew
homebrew_upgrade_all_packages: false
homebrew_installed_packages:
  - zsh
  - git
  - node
  - tart
  - tmux
  - starship
  - mono-libgdiplus
homebrew_cask_apps:
  - alacritty
  - font-fira-code-nerd-font
  - docker
  - brave-browser
  - firefox
  - google-chrome
  - visual-studio-code
  - rider
  - webstorm
  - utm
  - vlc
  - teamviewer
  - zoom
  - foxitreader
  - rectangle
  - git-credential-manager-core
  - 1password
homebrew_uninstalled_packages: []
homebrew_cask_uninstalled_apps: []

# Mas
mas_installed_apps:
  - { id: 1032155965, name: "Foxit PDF Reader"}
  - { id: 497799835, name: "Xcode"}
  - { id: 571213070, name: "DaVinci Resolve"}
mas_uninstalled_apps: []
mas_upgrade_all_apps: true
mas_signin_dialog: true