downloads: ~/.ansible-downloads/

# Dock
configure_dock: true

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Maps
  - Safari
  - Photos
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
  - Freeform
  - FaceTime
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 1
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2

# Homebrew
homebrew_taps:
  - homebrew/cask-fonts
  - isen-ng/dotnet-sdk-versions
  - homebrew/cask-versions
  - hashicorp/tap
homebrew_upgrade_all_packages: false
homebrew_installed_packages:
  - zsh
  - bash
  - bash-completion
  - git
  - nvm
  - tmux
  - starship
  - awscli
  - azure-cli
  - kubectl
  - helm
  - jq
  - bitwarden-cli
  - hashicorp/tap/terraform
homebrew_cask_apps:
  - dotnet-sdk7-0-100
  - dotnet-sdk6-0-400
  - alacritty
  - font-fira-code-nerd-font
  - docker
  - brave-browser
  - firefox
  - google-chrome
  - chromedriver
  - google-drive
  - visual-studio-code
  - rider
  - webstorm
  - datagrip
  - vlc
  - teamviewer
  - zoom
  - rectangle
  - 1password
  - adobe-creative-cloud
  - nextcloud
  - notion
  # - displaylink
  - insomnia
  - fork
  - microsoft-teams
  - tailscale
  - dbeaver-community
  - slack
  - logi-options-plus
  - syncthing
homebrew_uninstalled_packages:
  - tart
homebrew_cask_uninstalled_apps:
  - cloudflare-warp
  - utm
  - foxitreader
  - owasp-zap
  - git-credential-manager-core

# Mas
mas_installed_apps:
  - { id: 409203825, name: "Numbers"}
  - { id: 1291898086, name: "Toggl Track: Hours & Time Log"}
  - { id: 409201541, name: "Pages"}
  - { id: 409183694, name: "Keynote"}
  - { id: 1295203466, name: "Microsoft Remote Desktop"}
  - { id: 1351639930, name: "Gifski"}
  - { id: 1032155965, name: "Foxit PDF Reader"}
mas_uninstalled_apps:
  - { id: 506189836, name: "Harvest"}
  - { id: 571213070, name: "DaVinci Resolve"}
mas_upgrade_all_apps: true
mas_signin_dialog: true