downloads: ~/.ansible-downloads/

# Dock
configure_dock: true

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Maps
  - Safari
  - Photos
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 1
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2

# Homebrew
homebrew_taps:
  - homebrew/cask-fonts
  - isen-ng/dotnet-sdk-versions
  - homebrew/cask-drivers
  - homebrew/cask-versions
homebrew_upgrade_all_packages: false
homebrew_installed_packages:
  - zsh
  - git
  - node
  - tmux
  - starship
  - mono-libgdiplus
  - magic-wormhole
homebrew_cask_apps:
  - dotnet-sdk6-0-400
  - alacritty
  - font-fira-code-nerd-font
  - docker
  - brave-browser
  - firefox
  - firefox-developer-edition
  - google-chrome
  - chromedriver
  - google-drive
  - visual-studio-code
  - rider
  - webstorm
  - datagrip
  - vlc
  - teamviewer
  - zoom
  - rectangle
  - git-credential-manager-core
  - 1password
  - adobe-creative-cloud
  - nextcloud
  - notion
  - displaylink
homebrew_uninstalled_packages:
  - tart
homebrew_cask_uninstalled_apps:
  - utm
  - foxitreader

# Mas
mas_installed_apps:
  - { id: 409203825, name: "Numbers"}
  - { id: 409201541, name: "Pages"}
  - { id: 409183694, name: "Keynote"}
  - { id: 1475387142, name: "Tailscale"}
  - { id: 506189836, name: "Harvest"}
  - { id: 1455214828, name: "MQTT Explorer"}
  - { id: 1518425043, name: "Boop"}
  - { id: 1351639930, name: "Gifski"}
  - { id: 1032155965, name: "Foxit PDF Reader"}
  - { id: 497799835, name: "Xcode"}
  - { id: 571213070, name: "DaVinci Resolve"}
mas_uninstalled_apps: []
mas_upgrade_all_apps: true
mas_signin_dialog: true