downloads: ~/.ansible-downloads/

# Dock
configure_dock: true

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Calendar
  - Maps
  - Safari
  - Messages
  - Photos
  - FaceTime
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 1
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2
  - name: "Messenger"
    path: "/Applications/Messenger.app/"
    pos: 3
  - name: "System Preferences"

# Homebrew
homebrew_installed_packages:
  - git
  - fish
  - node
  - starship
  - tart
  - tmux
homebrew_cask_apps:
  - alacritty
  - font-fira-code-nerd-font
  - docker
  - brave-browser
  - google-chrome
  - visual-studio-code
  - rider
  - webstorm
  - utm
  - vlc
  - teamviewer
  - zoom

# Mas
mas_installed_apps:
  - { id: 1352778147, name: "Bitwarden"}
  - { id: 1032155965, name: "Foxit PDF Reader"}
  - { id: 1480068668, name: "Messenger"}
  - { id: 1451685025, name: "WireGuard"}
  - { id: 1147396723, name: "WhatsApp Desktop"}
  - { id: 497799835, name: "Xcode"}
  - { id: 571213070, name: "DaVinci Resolve"}
mas_uninstalled_apps: []
mas_upgrade_all_apps: true
mas_signin_dialog: true