- hosts: mac-m1

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: shell
      tags: ['shell']
